# Generated by Django 2.2.14 on 2020-08-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silvereye', '0001_initial'),
        ('bluetail', '0005_externalperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocdspackagedatajson',
            name='supplied_data',
            field=models.ForeignKey(null=True, on_delete=None, to='silvereye.FileSubmission'),
        ),
    ]
