# Generated by Django 2.2.14 on 2020-08-19 13:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetail', '0006_ocdspackagedatajson_supplied_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDSReleaseJSON',
            fields=[
                ('ocid', models.TextField(primary_key=True, serialize=False)),
                ('release_id', models.TextField()),
                ('release_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('package_data', models.ForeignKey(null=True, on_delete=None, to='bluetail.OCDSPackageDataJSON')),
            ],
            options={
                'db_table': 'bluetail_ocds_release_json',
            },
        ),
    ]
