# Generated by Django 2.2.14 on 2020-08-28 16:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluetail', '0006_ocdspackagedatajson_supplied_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCDSReleaseJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocid', models.TextField()),
                ('release_id', models.TextField()),
                ('release_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('package_data', models.ForeignKey(null=True, on_delete=None, to='bluetail.OCDSPackageDataJSON')),
            ],
            options={
                'db_table': 'bluetail_ocds_release_json',
                'unique_together': {('ocid', 'release_id')},
            },
        ),
    ]
