# Generated by Django 2.2.14 on 2020-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silvereye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.TextField(primary_key=True, serialize=False)),
                ('publisher_name', models.TextField()),
                ('contact_name', models.TextField(blank=True, default='')),
                ('contact_email', models.TextField(blank=True, default='')),
                ('contact_telephone', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'silvereye_publisher_metadata',
            },
        ),
    ]
