# Generated by Django 2.2.14 on 2020-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silvereye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=1024)),
                ('authority_type', models.CharField(max_length=1024)),
                ('source', models.CharField(max_length=1024)),
            ],
        ),
    ]
