# Generated by Django 2.2.14 on 2020-08-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silvereye', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publishermonthlycounts',
            unique_together={('publisher', 'date')},
        ),
    ]
