# Generated by Django 2.2.14 on 2020-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silvereye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='ocid_prefix',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisher_scheme',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
