# Generated by Django 2.2.14 on 2020-08-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silvereye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=1024)),
                ('contact_name', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('contact_email', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('contact_telephone', models.CharField(blank=True, default='', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'silvereye_publisher_metadata',
            },
        ),
        migrations.AlterField(
            model_name='publishermetrics',
            name='publisher_id',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publishermetrics',
            name='publisher_name',
            field=models.CharField(max_length=1024),
        ),
    ]
