# Generated by Django 2.2.14 on 2020-09-04 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silvereye', '0003_filesubmission_notice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCoverage',
            fields=[
                ('file_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='silvereye.FileSubmission')),
                ('tenders_field_coverage', models.FloatField(null=True)),
                ('awards_field_coverage', models.FloatField(null=True)),
                ('spend_field_coverage', models.FloatField(null=True)),
            ],
        ),
    ]
