#!/bin/sh

"$(dirname "$0")/manage" get_cf_data --file_path silvereye/data/cf_daily_csv/cf_files_2019-06-01_to_2020-09-06.zip --days 370 --load_data --publisher_submissions
"$(dirname "$0")/manage" import_authority_types

