#!/bin/sh

set -e

# Move to top level of project.
cd `dirname $0`/..

find . -name '*.pyc' -delete

# Recreate database contents.
PGPASSWORD=silvereye psql -d $DATABASE_URL -c "DROP SCHEMA IF EXISTS public CASCADE"
PGPASSWORD=silvereye psql -d $DATABASE_URL -c "CREATE SCHEMA public"

# Set up database.
"$(dirname "$0")/update"

# Create default superuser.
"$(dirname "$0")/manage" shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'admin')"

# Insert sample Contracts Finder data. (Remove this for empty deployment)
"$(dirname "$0")/insert_cf_data"
